spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5436/training_db
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cache:
    redis:
      time-to-live: 60000
    type: redis
    host: localhost
    port: 6379
    isCredential: false
    prefix: training_batch17
    default-ttl: 60

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: 9f3c2b6a4e1d8f7c5a9b0e3d2c6f8a1b4d7e9c2f6a8b1d3e5c7f9a0b2d4e6f8c1a3b5d7f9e2c4a6b8d0f1e3c5a7b9d2
  expiration: 86400000

server:
  port: 8081
  servlet:
    context-path: /product-service

kafka:
  bootstrap-servers: localhost:9092